credentials:
  usernames:
    bqxiao:
      email: bqxiao123@gmail.com
      name: quanbao xiao
      password: '$2b$12$Zudnc/bKPirFHg/fnqbaiu7qHDxRKmYnO3LlLwPcAmTT8.ryR3TA2' # Placeholder for hashed password of 'abc'
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$pnwEkqdrleo5/eOlUXGKu.ekBZwjh4kjQ6iW59.40S91A/UEQkE/S # Placeholder for hashed password of 'def'
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com